### ISSUE TITLE
How do I get the data?

### ISSUE THREAD

**Issue by densanx** [Unit2795/PowershellExpect#15]
![image](https://github.com/Unit2795/PowershellExpect/assets/33722478/0e01111f-5e79-4dce-bfae-49c981ece1bb)

10.47.0.2 - Android TV box
```
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\powershellexpect\PowershellExpect.psm1'
$ADB = 'C:\Distr\Install\adb\adb.exe'
$IP= '10.47.0.2'

spawn "$ADB connect $IP" 5
expect 'connected to'
$Model = Send "$ADB shell getprop ro.product.model /n"
Expect -EOF
Write-Host $Model
```

**Comment by Unit2795** [comment]
Working on a fix for this with a patch for some of the other issues. Should be ready tomorrow. You'll then be able to extract the results of commands into a variable.

**Comment by Unit2795** [comment]
A PR has been opened with a fix. Should this be merged your script would likely resemble the following. Will keep you posted
```powershell
Import-Module 'C:\Program Files\WindowsPowerShell\Modules\powershellexpect\PowershellExpect.psm1'
$ADB = 'C:\Distr\Install\adb\adb.exe'
$IP= '10.47.0.2'

$process = Spawn -Timeout 5 -EnableLogging
$process.Send("$ADB connect $IP")
$process.Expect("connected to")
# Send the command, ignore the input line, and wait for the output to be idle for 5 seconds
$Model = $process.SendAndWait("$ADB shell getprop ro.product.model", 1, 5)
Write-Host $Model
```

Looking closer at this, I think you might be able to automate this without the use of this automation library like so:
```powershell
$connect = & "$ADB connect $IP"
if ($connect -match "connected to")
{
  $Model = & "$ADB shell getprop ro.product.model"
  Write-Host $Model
}
```
You pipe the result of your commands into a variable, and depending on the result of the first, you execute the command to retrieve the model. This may or may not work for your use case.

**Comment by Unit2795** [comment]
1.2.0 has been released! Let me know if you run into any issues or need assistance.

Thank you for submitting this issue and best of luck on your projects!
